### ISSUE TITLE
[DOCS] Readme

### ISSUE THREAD

**Issue by ManishBisht777** [FrontendFreaks/Official-Website#10]
### Description

Create Readme for the project

- What's the project for
- features
- how to run it on local
- and many more things

**Comment by mnamesujit** [comment]
Hi @ManishBisht777  can you explain little bit more about that, because I think readme is already created for this project.

**Comment by ManishBisht777** [comment]
updated the issue description

**Comment by nnisarggada** [comment]
I would like to work on this

**Comment by ManishBisht777** [comment]
sure @nnisarggada Assigned to you

**Comment by ManishBisht777** [comment]
https://github.com/EddieHubCommunity/BioDrop  you can refer to this readme for reference

**Comment by nsundriyal62** [comment]
@ManishBisht777 this is already assigned sir.

So should I work in this or not?

**Comment by ManishBisht777** [comment]
@nsundriyal62 just noticed. you can take some other issues from the issues section

**Comment by nsundriyal62** [comment]
Ok sir 👍
