### ISSUE TITLE
Update the Content of  Time Complexity Page of DSA in JS

### ISSUE THREAD

**Issue by sujitmemane** [FrontendFreaks/Official-Website#100]
### Description

*Description:*
This issue is for updating the content of Time Complexity Page  of DSA (Data Structures and Algorithms) section  in our project. Here are the specific changes needed:

*1. What is on this Page ? - Section*
- It should contain the list of topics covered in the video.

*2. This Page should Contain Tabs - Learn and Assignment*
- Create tabs for "Learn" and "Assignment" sections.

*3. Learn Section should contain Video and Notes*
- In the "Learn" section, add subsections for videos and notes.

*4. Assignment section should contain assignments*
- In the "Assignment" section, include assignments related to the topics.

*5. To update the content*
- Go to the Content folder of the root directory, then navigate to the batch folder, and then navigate to the DSA folder to make changes in the 'time-complexity.mdx' file.

*Content Check:*
For reference, please check the current content in the [Time Complexity  Content](https://github.com/FrontendFreaks/DSA-in-JavaScript/blob/main/Time%20Complexity/README.md) 

*Additional Information:*
Please make sure to maintain consistency with the existing structure and style of the project. Let's enhance the DSA page to make it more user-friendly and informative.

**Comment by nsundriyal62** [comment]
just completed loop page of dsa 
can i work on this ?

assign it to me sir.

**Comment by kartikp962** [comment]
Can i work on this sir?

Please assign it to me.

**Comment by sujitmemane** [comment]
> Can i work on this sir?
> 
> Please assign it to me.

Assigned to you - complete it ASAP

**Comment by Vishal-raj-1** [comment]
@kartikp962 Any Update?

**Comment by nsundriyal62** [comment]
@kartikp962 if you facing any issue then you can ask buddy, i recently solved 2 issues of these types 
or in case you not started it @Vishal-raj-1 you can assign it to me

**Comment by nsundriyal62** [comment]
@Vishal-raj-1 there is no update from @kartikp962  side.

can i work on this issue

**Comment by sujitmemane** [comment]
@nsundriyal62 assigned to you - please complete it asap and raise pr

**Comment by nsundriyal62** [comment]
working on it sir
