### ISSUE TITLE
Update the Content of Polyfills Page of DSA in JS

### ISSUE THREAD

**Issue by sujitmemane** [FrontendFreaks/Official-Website#102]
### Description

*Description:*
This issue is for updating the content of Polyfills Page  of DSA (Data Structures and Algorithms) section  in our project. Here are the specific changes needed:

*1. What is on this Page ? - Section*
- It should contain the list of topics covered in the video.

*2. This Page should Contain Tabs - Learn and Assignment*
- Create tabs for "Learn" and "Assignment" sections.

*3. Learn Section should contain Video and Notes*
- In the "Learn" section, add subsections for videos and notes.

*4. Assignment section should contain assignments*
- In the "Assignment" section, include assignments related to the topics.

*5. To update the content*
- Go to the Content folder of the root directory, then navigate to the batch folder, and then navigate to the DSA folder to make changes in the 'polyfills.mdx' file.

*Content Check:*
For reference, please check the current content in the [Polyfills Content](https://github.com/FrontendFreaks/DSA-in-JavaScript/blob/main/Array/Polyfill.md) 

*Additional Information:*
Please make sure to maintain consistency with the existing structure and style of the project. Let's enhance the DSA page to make it more user-friendly and informative.

**Comment by Abhish7k** [comment]
I would like to work on this, please assign me this issue.

**Comment by sujitmemane** [comment]
> I would like to work on this, please assign me this issue.
Assigned Issue to You ; Submit PR ASAP

**Comment by Abhish7k** [comment]
Hey @sujitmemane, it shows 404 when I click on the [learn](https://frontendfreaks.vercel.app/batch/learn/html/b) tab.
