### ISSUE TITLE
Update the content of  String Page of DSA in JS

### ISSUE THREAD

**Issue by sujitmemane** [FrontendFreaks/Official-Website#103]
### Description

*Description:*
This issue is for updating the content of String Page  of DSA (Data Structures and Algorithms) section  in our project. Here are the specific changes needed:

*1. What is on this Page ? - Section*
- It should contain the list of topics covered in the video.

*2. This Page should Contain Tabs - Learn and Assignment*
- Create tabs for "Learn" and "Assignment" sections.

*3. Learn Section should contain Video and Notes*
- In the "Learn" section, add subsections for videos and notes.

*4. Assignment section should contain assignments*
- In the "Assignment" section, include assignments related to the topics.

*5. To update the content*
- Go to the Content folder of the root directory, then navigate to the batch folder, and then navigate to the DSA folder to make changes in the 'string.mdx' file.

*Content Check:*
For reference, please check the current content in the [String Content](https://github.com/FrontendFreaks/DSA-in-JavaScript/blob/main/String/README.md) 

*Additional Information:*
Please make sure to maintain consistency with the existing structure and style of the project. Let's enhance the DSA page to make it more user-friendly and informative.

**Comment by AjinkyaD3** [comment]
I would like to work on it . please assign it to me

**Comment by nsundriyal62** [comment]
can you assign this to me sir 

i almost completed it 

i have template too for all these newly issues

**Comment by sujitmemane** [comment]
> can you assign this to me sir
> 
> i almost completed it
> 
> i have template too for all these newly issues

Assigned to you - complete it ASAP
