### ISSUE TITLE
Update the content of Recursion Page of DSA in JS

### ISSUE THREAD

**Issue by sujitmemane** [FrontendFreaks/Official-Website#104]
### Description

*Description:*
This issue is for updating the content of Recursion Page  of DSA (Data Structures and Algorithms) section  in our project. Here are the specific changes needed:

*1. What is on this Page ? - Section*
- It should contain the list of topics covered in the video.

*2. This Page should Contain Tabs - Learn and Assignment*
- Create tabs for "Learn" and "Assignment" sections.

*3. Learn Section should contain Video and Notes*
- In the "Learn" section, add subsections for videos and notes.

*4. Assignment section should contain assignments*
- In the "Assignment" section, include assignments related to the topics.

*5. To update the content*
- Go to the Content folder of the root directory, then navigate to the batch folder, and then navigate to the DSA folder to make changes in the 'recursion.mdx' file.

*Content Check:*
For reference, please check the current content in the [Recursion Content](https://github.com/FrontendFreaks/DSA-in-JavaScript/blob/main/Recursion/README.md) 

*Additional Information:*
Please make sure to maintain consistency with the existing structure and style of the project. Let's enhance the DSA page to make it more user-friendly and informative.

**Comment by AjinkyaD3** [comment]
I would like to work on it . please assign it to me

**Comment by sujitmemane** [comment]
> I would like to work on it . please assign it to me

Assigned to You ; Submit your PR ASAP

**Comment by Vishal-raj-1** [comment]
@AjinkyaD3 you have to raise the PR in Frontend Freak Repo. Not in your repo

**Comment by Vishal-raj-1** [comment]
@AjinkyaD3 Any Update on this Issue?

**Comment by nsundriyal62** [comment]
if it's not started then you can assign it to me

**Comment by nsundriyal62** [comment]
in case there is no update in this issue then you can assign this to me
i am gonna raise a pr
i almost solved it but waiting for @Vishal-raj-1 response sir

**Comment by sujitmemane** [comment]
> in case there is no update in this issue then you can assign this to me i am gonna raise a pr i almost solved it but waiting for @Vishal-raj-1 response sir
Assigned to You

**Comment by Shashankpantiitbhilai** [comment]
In case there is  no update please assign this issue to me sir.I am working on it currently
