### ISSUE TITLE
IMPROVEMENT: Remove the "@next/font" warning 

### ISSUE THREAD

**Issue by saniyasaher20** [FrontendFreaks/Official-Website#106]
### Description

HOW TO REPRODUCE THE WARNING:

1. Open the project in code editor
2. Run this command `npm run dev`
3. You will see this warning->
**`warn Your project has '@next/font' installed as a dependency, please use the built-in 'next/font' instead. The '@next/font' package will be removed in Next.js 14. `**

This is the warning screenshot:
![next font warning](https://github.com/FrontendFreaks/Official-Website/assets/43143907/0d86cab1-5d28-4a78-933b-72b457c90997)

Refer to this next js doc for more information: https://nextjs.org/docs/pages/building-your-application/upgrading/codemods#use-built-in-font

**Comment by Huzaifa785** [comment]
I would love to solve this issue, looking more into it.

**Comment by saniyasaher20** [comment]
next/font changed to built in nextjs font #109
