### ISSUE TITLE
[Feat] Improve Linear and Binary Search Page

### ISSUE THREAD

**Issue by ranitasahaa1230** [FrontendFreaks/Official-Website#112]
### Description

Description:
Adding Content and Improving Linear and Binary Search Page
https://frontendfreaks.vercel.app/batch/dsa/search

**Comment by ranitasahaa1230** [comment]
I want to work on this issue, Can I take this up, @Vishal-raj-1 ?

**Comment by sujitmemane** [comment]
> I want to work on this issue, Can I take this up, @Vishal-raj-1 ?

Assigned to you - complete it ASAP

**Comment by Vishal-raj-1** [comment]
Hey @ranitasahaa1230 Any Update?

**Comment by nsundriyal62** [comment]
if its not started then you can assign it to me sir.

**Comment by ranitasahaa1230** [comment]
Hi @Vishal-raj-1, I have started and will raise the PR by Sunday. Is there any format or anything that the content should look like?

**Comment by ranitasahaa1230** [comment]
> Hey @ranitasahaa1230 Any Update?


Hi @Vishal-raj-1, I have started and will raise the PR by Sunday. Is there any format or anything that the content should look like?
