### ISSUE TITLE
Docs menu option only seen on home page

### ISSUE THREAD

**Issue by Huzaifa785** [FrontendFreaks/Official-Website#113]
### Description

When we go to the [website](https://frontendfreaks.vercel.app/), the `docs` menu option is seen but on other pages its not there.

**On Home page** 👇🏼
<img width="1440" alt="Screenshot 2023-10-03 at 12 31 52 PM" src="https://github.com/FrontendFreaks/Official-Website/assets/70282139/e75b4b0e-ea88-4ce2-9131-abe8ecc758cc">

**On other pages** 👇🏼
<img width="1440" alt="Screenshot 2023-10-03 at 12 32 27 PM" src="https://github.com/FrontendFreaks/Official-Website/assets/70282139/b4a2b654-741e-43e1-8af5-dbfaca654577">

**Comment by ManishBisht777** [comment]
@Huzaifa785 Thanks for pointing it out, you want to work on it?

**Comment by nsundriyal62** [comment]
i want to work on this issue sir
can you assign it to me?

**Comment by Huzaifa785** [comment]
Hey @ManishBisht777 
sure I'm working on it, will update soon.
