### ISSUE TITLE
update the linear and binary search section of dsa in javascript section

### ISSUE THREAD

**Issue by Hrishap** [FrontendFreaks/Official-Website#114]
### Description

want to add content related to linear and binary search in javascript  in the desired manner

**Comment by Hrishap** [comment]
Thanks for guiding i will follow the guideline please ASSIGN ME THIS ISSUE

**Comment by ManishBisht777** [comment]
sure @Hrishap Assigned to you

**Comment by Vishal-raj-1** [comment]
@Hrishap Any Update?

**Comment by nsundriyal62** [comment]
i would like to work on this issue it its not started

**Comment by Vishal-raj-1** [comment]
Sure @nsundriyal62 go ahead
