### ISSUE TITLE
Toggle missing on other pages

### ISSUE THREAD

**Issue by ThotaRitikesh** [FrontendFreaks/Official-Website#117]
### Description
 dark/light mode only available on home page but technically it should be accessable thought the website but found missing in other pages.
![Screenshot (567)](https://github.com/FrontendFreaks/Official-Website/assets/91207994/1bfc83a6-4d51-47f6-bafb-aafa3e63a12b)
![Screenshot (568)](https://github.com/FrontendFreaks/Official-Website/assets/91207994/432d78d9-47b5-4dc1-8d08-562f59344b82)

**Comment by ThotaRitikesh** [comment]
This has been done (global mode-Toggle) #117
![Screenshot (569)](https://github.com/FrontendFreaks/Official-Website/assets/91207994/049becf0-b9ed-4875-8495-80ff7ec97179)

**Comment by Tanmay-Joshi73** [comment]
@ThotaRitikesh  hey Are u working on this Issue?

**Comment by ThotaRitikesh** [comment]
I worked on this bro but i was late to raise pr.
