### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Mohak973** [FrontendFreaks/Official-Website#120]
### Description

The footer is present on a website landing page but is not present on other pages.

###Screentshot

This is the landing page

<img width="940" alt="frontend_freaks_fotter" src="https://github.com/FrontendFreaks/Official-Website/assets/91401503/905728e4-1f1d-42e7-b1a1-5ba752a63874">

This is the learn page

<img width="944" alt="frontend_freaks_fotter2" src="https://github.com/FrontendFreaks/Official-Website/assets/91401503/d904b670-ee82-4756-968c-a85815329ef3">

**Comment by ThotaRitikesh** [comment]
should i work on this @Mohak973 ?

**Comment by Mohak973** [comment]
I am working on this @ThotaRitikesh

**Comment by ManishBisht777** [comment]
@ThotaRitikesh @Mohak973 Please wait for the maintainers to assign the issues before working this can create unnecessary confusion among contributors and they might end up working on the same issue and making pr for the same

**Comment by ManishBisht777** [comment]
Since @Mohak973 is working on this i am assigning this to him but from next time please wait for the issue to get assigned

**Comment by saniyasaher20** [comment]
@Mohak973 Are you working on this?

**Comment by saniyasaher20** [comment]
This issue is solved, please close this.
