### ISSUE TITLE
Credits section

### ISSUE THREAD

**Issue by Pavan-Sai-padavala** [FrontendFreaks/Official-Website#126]
### Description

Credits section at the bottom of the page gives honor to our open-source contributors.
![image](https://github.com/FrontendFreaks/Official-Website/assets/72682254/0ad48c9e-b944-4f5a-bfce-b905660a162f)
![image](https://github.com/FrontendFreaks/Official-Website/assets/72682254/2bba4cd0-0cac-4b6b-9d48-962030967859)

**Comment by ManishBisht777** [comment]
Should we really need it?

it is already present at the readme

**Comment by Vishal-raj-1** [comment]
Hey @Pavan-Sai-padavala After 1 month, after considering active open source contributor. I will add Official Team Section on Frontend Freaks. 

We will not add whole open source contributor. So for now let's close this issue
