### ISSUE TITLE
DSA in JavaScript Card is missing on Home page and Getting Started Page

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#139]
### Description

# Description

Learn, Build & Hire Batch card is present on the main page and also on the getting started page. But DSA in JavaScript card is not there.

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/0b36adf5-76de-4098-8061-057891158f00)

**Comment by Tanmay-Joshi73** [comment]
can i work on this Issue?

**Comment by Tanmay-Joshi73** [comment]
And what icon should i use for DSA in JS
