### ISSUE TITLE
DSA in JavaScript is not present in the navbar

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#140]
### Description

Add DSA in JavaScript Navlink 

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/bdd08ac4-ceef-4680-b9a1-4d00c82c1121)

**Comment by Huzaifa785** [comment]
on it, adding it and will update soon

**Comment by Huzaifa785** [comment]
on which page should it go on?
