### ISSUE TITLE
Remove Unclear with concept? Watch this component and video from Assignment tab

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#142]
### Description

# Bug

Video and source code is already present on the Learn Tab. So it is unnecessary to add same content on different tab.

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/38175c68-6c0e-4f67-966e-3a0d18885c1a)

Remove this section from all the assignments pages.

**Comment by Ayush17112002** [comment]
Hi @Vishal-raj-1, I have removed the video as mentioned in the issue.
