### ISSUE TITLE
[Feat] Add: Notes for ReactJS in > Build Batch > ReactJS > Fundamentals

### ISSUE THREAD

**Issue by SanskritiGupta05** [FrontendFreaks/Official-Website#144]
### Description

When I saw the Getting Started with React JS video I wrote down some extensive notes in my Notion app, and I'd like to contribute those notes to the website. 
- Please assign this issue to me
-  Please add Hacktoberfest tag to the issue. 😊

**Comment by Vishal-raj-1** [comment]
Go Ahead @SanskritiGupta05 

don't worry about the tag, I have added the Hacktoberfest tag to the whole repo, so don't need to add it individually on all PR or Issues

**Comment by SanskritiGupta05** [comment]
Thank you so much, I'll start working on it 😄
