### ISSUE TITLE
DSA in js Card css missing

### ISSUE THREAD

**Issue by Shyam3050** [FrontendFreaks/Official-Website#157]
### Description

![Screenshot (123)](https://github.com/FrontendFreaks/Official-Website/assets/91086813/61a7639e-f51d-4509-9e0e-e922f935854f)

Just Change text-xs -> to text-md max-w-xs -> max-w-md on tracks.tsx which is inside the component folder.

This is a beginner-friendly issue for newbie.

**Comment by nsundriyal62** [comment]
can  i solve this sir?
assign it to me
@Shyam3050

**Comment by Shyam3050** [comment]
do it then raise a PR @Vishal-raj-1  will review it if everything ok then it will be merged.

**Comment by nsundriyal62** [comment]
ok sir
