### ISSUE TITLE
Advance Sorting "Page is not" found after linking on it

### ISSUE THREAD

**Issue by imvinayak32** [FrontendFreaks/Official-Website#163]
### Description

# Bug 
Right now, if you go to **Advance Sorting** page under **DSA in Javascript** it shows "Page is not found", which is bug.

# Screenshot
![image](https://github.com/FrontendFreaks/Official-Website/assets/131988601/387270be-c0c8-43bf-a501-f3972ee5e1e5)

# Solution
We have to add the page link correctly into the code of this project.

**Comment by Tanmay-Joshi73** [comment]
Hey Please Assigned Me To This ,I also solved the issue

**Comment by Tanmay-Joshi73** [comment]
Hey I Solved This Issue and also raise a PR

**Comment by nsundriyal62** [comment]
I that case
Brother Raise a pr

**Comment by Tanmay-Joshi73** [comment]
Hey Also Raised a PR

**Comment by imvinayak32** [comment]
Already this issue is completed by @Tanmay-Joshi73  & also reviewed by @Vishal-raj-1. So I am closing this issue.
