### ISSUE TITLE
Under DSA in Javascript section, String video is not available as iframe 

### ISSUE THREAD

**Issue by imvinayak32** [FrontendFreaks/Official-Website#164]
### Description

# Bug
Under DSA in Javascript section, in String page, it's video is not available as iframe, it will redirect you to youtube.

# Screenshot
- Problem exists only in String section.
![Screenshot from 2023-10-07 12-20-00](https://github.com/FrontendFreaks/Official-Website/assets/131988601/4a19cc80-690d-44b6-a426-dd2615d49e75)
- Otherwise, videos are working fine in other sections
![image](https://github.com/FrontendFreaks/Official-Website/assets/131988601/f362d722-2bf2-42a3-b7d7-015025cca57f)

# Solution
Add iframe of String video like in Array video.

**Comment by Tanmay-Joshi73** [comment]
hey can i work on this issue ,Please Assigned me?

**Comment by nsundriyal62** [comment]
@imvinayak32 thanks man for pointing out that issue
