### ISSUE TITLE
HTML Interview Questions are not available in official website of frontendfreaks

### ISSUE THREAD

**Issue by kashish119** [FrontendFreaks/Official-Website#170]
https://frontendfreaks.vercel.app/batch/learn/html/basic
![image](https://github.com/FrontendFreaks/Official-Website/assets/76028768/225916e2-9173-4aa6-bac8-c048c4749f72)

**Comment by saniyasaher20** [comment]
I would like to work on this. PLease assign it to me

**Comment by imvinayak32** [comment]
I can work on this please assign me @nsundriyal62 .

**Comment by nsundriyal62** [comment]
@Vishal-raj-1 

is there any feedback on this issue sir?

**Comment by Vishal-raj-1** [comment]
I will merge the first PR which solve this issue. You can refer React Interview Questions Section for reference

**Comment by Vishal-raj-1** [comment]
Any update? @kashish119 @imvinayak32 @saniyasaher20 @nsundriyal62

**Comment by nsundriyal62** [comment]
it's done sir
sorry for late response.
