### ISSUE TITLE
Wrong Redirecting

### ISSUE THREAD

**Issue by Tanmay-Joshi73** [FrontendFreaks/Official-Website#174]
![image](https://github.com/FrontendFreaks/Official-Website/assets/124510117/82eddb11-222a-4e5b-bc8f-65cf27a201b2)

> Here Card1 and Card2 are works as a link and redirecting it to the same page again

![image](https://github.com/FrontendFreaks/Official-Website/assets/124510117/da49f91f-086e-4aa3-aab7-a67a16d5f50f)

> In the code <Card href="#" Which is in the same page so when click on it it take user to same page 

> Is That Necessary?

**Comment by Tanmay-Joshi73** [comment]
hey @Vishal-raj-1  Both Card1 And Card2  are redirecting to the same page ,Is That Necessary?

**Comment by saniyasaher20** [comment]
The main focus is to show how to make cards, so there's no need to link those cards to any other page. That's why `href=#` is used, it will redirect to the same page.

**Comment by Tanmay-Joshi73** [comment]
ok
