### ISSUE TITLE
Interview Questions on CSS Flex Crash Course Not Available

### ISSUE THREAD

**Issue by khushijohri2001** [FrontendFreaks/Official-Website#175]
### Description

# Bug 

The interview Questions tab under Learn Batch > CSS > Flex Crash Course does not contain interview questions. I would like to update the page. Please assign this issue to me.

<img width="1402" alt="Screenshot 2023-10-07 at 6 30 13 PM" src="https://github.com/FrontendFreaks/Official-Website/assets/65448358/55f48f65-701e-4f05-8ddb-7302ed59fd4e">

**Comment by imvinayak32** [comment]
Please assign this to me @nsundriyal62

**Comment by Vishal-raj-1** [comment]
whoever want to work on this issue, just raise the PR

**Comment by imvinayak32** [comment]
From where should i add the question like any specific source?? @Vishal-raj-1
