### ISSUE TITLE
Mentorship button at footer

### ISSUE THREAD

**Issue by utkarsh0903** [FrontendFreaks/Official-Website#179]
### Description

**BUG**
In footer at home page we have mentorship button which takes user to discord community.

**Screenshots**
![image](https://github.com/FrontendFreaks/Official-Website/assets/81482801/9fa6d759-9dda-4a51-a7d6-7a1f9e11aa46)

 
**Expected behavior**
Either button text to be changed to community or if keeping mentorship it should redirect to batch page.
Like syncing with the two button we have at our home page. Look at the below image.
![image](https://github.com/FrontendFreaks/Official-Website/assets/81482801/1f09ca95-bcbe-4d67-aab1-63ce19fab2c8)

I would like to contribute to it. Please assign. Thanks.
@ManishBisht777

**Comment by ManishBisht777** [comment]
Make sense @utkarsh0903 , sure assigned to you

**Comment by utkarsh0903** [comment]
So what should I do, redirect it to batch or change it's text to Join Community.

**Comment by Vishal-raj-1** [comment]
@utkarsh0903 Join Community, Cause other options already points to batch
