### ISSUE TITLE
Want to improve this page : Basic sorting

### ISSUE THREAD

**Issue by ankushtripathii** [FrontendFreaks/Official-Website#180]
Can you assign me to add content on the basic sorting page?
BUG

![Screenshot 2023-10-08 015154](https://github.com/FrontendFreaks/Official-Website/assets/89534251/5acb9d91-2459-4173-8558-d49fe82d2025)

Also, Can I add the Coding-Ninja sorting question on an assignment related to bubble sort, insertion sort, and selection sort?

**Comment by Vishal-raj-1** [comment]
this issue is already resolved
