### ISSUE TITLE
Fix Menu Option Active State Detection Issue

### ISSUE THREAD

**Issue by Huzaifa785** [FrontendFreaks/Official-Website#195]
I have identified an issue where the menu option is not being recognized as active. Like whenever we go on a specific page, the user might get confused on which page he/she is on.

<img width="1439" alt="Screenshot 2023-10-11 at 9 48 51 PM" src="https://github.com/FrontendFreaks/Official-Website/assets/70282139/0ce1dc1c-deb1-4a39-9caf-4692a963b5dc">

**Comment by Allan2000-Git** [comment]
you need to have a active state. using js, you can implement

**Comment by Huzaifa785** [comment]
I made the changes, now we will be able to recognize on which menu option we are on
