### ISSUE TITLE
Mistake in Readme.md file

### ISSUE THREAD

**Issue by MacMillon-VS** [FrontendFreaks/Official-Website#197]
### Description

Description 
Repo name in git clone command is not correct and cd cmd not correct. So facing issue while setting repo locally  

error link: git clone https://github.com/frontend-freaks/frontend-freaks-website.git

![image](https://github.com/FrontendFreaks/Official-Website/assets/93966956/f00e77fa-9925-43b5-a144-283a4743d46d)

Please assign it to me. I would like to fix it

**Comment by rishabh-318** [comment]
Thanks for creating the issue but it is already resolved and i did raised a PR too.

U can work on another issue.

**Comment by MacMillon-VS** [comment]
You're welcome! I'm glad to hear that the issue has been resolved and that you've raised a pull request.

Certainly, I'll look for another issue to work on. If you have any specific suggestions or if there's anything in particular you'd like me to focus on, please let me know. I'm here to help and contribute to the project.

**Comment by rishabh-318** [comment]
Currently most of the issues are assigned or somebody is working on those issues so, keep in touch with the community, soon you will get some good first issue to start with.
