### ISSUE TITLE
[Feat] Table of contents

### ISSUE THREAD

**Issue by ManishBisht777** [FrontendFreaks/Official-Website#2]
### Description

Add table of contents for each page at the side

### Screenshots

Example
![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/89926834/acc96c0e-f021-48c2-8601-06c924d2be26)

**Comment by Vishal-raj-1** [comment]
Hey @ManishBisht777 Considering we have 4 tabs (Video/Notes, Interview Questions, Assignment, Playground (upcoming)). 

Do we really need table of content? Isn't it over engineering

**Comment by ManishBisht777** [comment]
I do feel like but ig it would be helpful for notes section

**Comment by ManishBisht777** [comment]
lets move this to discussion

**Comment by Vishal-raj-1** [comment]
@ManishBisht777 Generally Notes are less than 500 words, So I don't think it will be good idea.

**Comment by ManishBisht777** [comment]
cool then lets come to this later
