### ISSUE TITLE
Doubt Discussion must be a parameter should be included in them  and it will be one more such type of thing..

### ISSUE THREAD

**Issue by anmoldeep38** [FrontendFreaks/Official-Website#200]
### Description

![Screenshot (609)](https://github.com/FrontendFreaks/Official-Website/assets/87927563/afe5d60a-3470-4bc1-ac53-06f20e6f2f99)

**Comment by Vishal-raj-1** [comment]
This is the old website. This is current website: https://frontendfreaks.vercel.app/
