### ISSUE TITLE
Want to add "HTML in Hindi" video of web dev Bootcamp in batch/learn/html/basic section

### ISSUE THREAD

**Issue by anamika133m** [FrontendFreaks/Official-Website#203]
### Description

I want to add HTML in Hindi video to the batch/learn/basic section in the frontend freaks website, where only English video is provided.

the video that I want to add below the English video is https://www.youtube.com/live/gq69z153tf0?si=Sr--mxO_ChjRyEBX

![Screenshot (686)](https://github.com/FrontendFreaks/Official-Website/assets/91742884/53f19a93-1f96-4b0c-8477-a613e7909e7a)

**Comment by Vishal-raj-1** [comment]
@anamika133m Thanks for pointing out this issue. 

I also want to implement this feature, but rather than showing two videos in vertical. I would suggest you to create a tab of Hindi and English.

The default tab should be Hindi.

Can you implement this?

**Comment by anamika133m** [comment]
Yes, I can do this. 
So we have to make two tabs Hindi and English and the notes/code below will come in both tabs?

**Comment by Vishal-raj-1** [comment]
@anamika133m Nope, Notes will be the same, just after watching now there should be another tab. Hindi & English

**Comment by anamika133m** [comment]
Ok! Got it, I'm working on this and will complete it ASAP.

**Comment by anamika133m** [comment]
Please look at this and let me know if it is OK.
![Screenshot (687)](https://github.com/FrontendFreaks/Official-Website/assets/91742884/2770e035-1b81-45fd-8d8c-59aedf76cd78)

**Comment by Vishal-raj-1** [comment]
@anamika133m Perfect 🚀
