### ISSUE TITLE
[Feat] Adding Resume templates for reference under the Hire Batch Tab

### ISSUE THREAD

**Issue by bhawna-107** [FrontendFreaks/Official-Website#205]
### Description

In the Hire Batch Tab within the profile and resume tab I think that after the resume video we can provide some useful and good resume templates for reference from overleaf as @Vishal-raj-1 you have mentioned in your video. It will be a  helpful resource to complement the resume video.

![issue1](https://github.com/FrontendFreaks/Official-Website/assets/57867810/439c3a43-84f1-472b-9147-cd1855c8473a)

Some overleaf resume examples that i think would be good to add. 
https://www.overleaf.com/latex/templates/jakes-resume-anonymous/cstpnrbkhndn
https://www.overleaf.com/latex/templates/jakes-resume/syzfjbzwjncs
https://www.overleaf.com/latex/templates/faangpath-simple-template/npsfpdqnxmbc
https://www.overleaf.com/latex/templates/software-engineer-resume/gqxmqsvsbdjf
https://www.overleaf.com/latex/templates/deedy-cv/bjryvfsjdyxz
https://www.overleaf.com/latex/templates/70-plus-ats-rating-resume-template/ssprfsctyddz
https://www.overleaf.com/latex/templates/resume-template/gxymbfbhdjwk

Please review it and you can add more examples too.

**Comment by bhawna-107** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Vishal-raj-1** [comment]
Go Ahead @bhawna-107
