### ISSUE TITLE
[Feat] Highlight/Announcement Section above Navbar

### ISSUE THREAD

**Issue by khushijohri2001** [FrontendFreaks/Official-Website#212]
### Description

The best thing about Frontend Freaks is that it's completely free and we should highlight this fact at the very top of the website to attract and engage more people. I want to create a highlight/announcement section above the navbar where we can announce special offers as well but currently, I'm adding it for highlighting that "Everything is free".

**Comment by nsundriyal62** [comment]
it's a good idea @khushijohri2001 
what's your opinion on this @Vishal-raj-1 sir

**Comment by ujjawalsh99** [comment]
It's a good issue @khushijohri2001 👏
