### ISSUE TITLE
[Feat] To add interview questions inside - Learn Batch > JavaScript > Basic Introduction 

### ISSUE THREAD

**Issue by hemant14050** [FrontendFreaks/Official-Website#217]
### Description

# Feature:
- Interview Questions on JavaScript

# Solution
- To add Interview Questions tab, at the right of Assignment tab
- To show Interview Questions after clicking this tab

![image](https://github.com/FrontendFreaks/Official-Website/assets/112842857/ff612bb0-5b77-4e1d-a68d-baea7fa7b330)

**Comment by hemant14050** [comment]
Please assign it to me.
I want to work on this.

**Comment by Vishal-raj-1** [comment]
go ahead @hemant14050
