### ISSUE TITLE
Fix: Button Style and Naming Consistency

### ISSUE THREAD

**Issue by khushijohri2001** [FrontendFreaks/Official-Website#222]
### Description

There is no consistency in the styling and naming of buttons. Somewhere the buttons/links are rounded and somewhere it is squared. In the header, the Mentorship button has the link to Discord but it should be Join Community. 

Rename Join Community to Join Discord Community, to specify and give a hit of what the community is like.

(Changes in Header, Footer, and other sections)

**Comment by ManishBisht777** [comment]
Thanks for raising a pr please from next time raise only one pr at a time and before working please make wait for the issue to get assigned

**Comment by khushijohri2001** [comment]
@ManishBisht777 okay definitely
