### ISSUE TITLE
Mentorship button next to theme toggle is not required

### ISSUE THREAD

**Issue by barkha-gupta** [FrontendFreaks/Official-Website#226]
### Description

**Problem** 
- Landing page already have Join Mentorship button.  
- The one next to theme toggle is uncalled-for and confuses as both the Mentorship buttons links to different things

![Screenshot 2023-10-18 004149](https://github.com/FrontendFreaks/Official-Website/assets/114416337/90790b93-5e15-4650-a0b3-d3ca762e62e6)

**Solution**
* We can remove it to make landing page look clearer.

**Comment by barkha-gupta** [comment]
I can remove it, if its assigned to me.

**Comment by barkha-gupta** [comment]
I would like this issue to be assigned to me.

**Comment by khushijohri2001** [comment]
@barkha-gupta Actually I have updated the button and its Join Discord Community button now. I have raised a pr for the same

**Comment by barkha-gupta** [comment]
@khushijohri2001 I understand. I mentioned the button to be removed all together. I am just waiting for the issue to be assigned by following the guidelines.

**Comment by ManishBisht777** [comment]
hey @malthaf9 please wait for maintainer to assign the issue this will create unnecessary confusion among contributors and duw to this many contributors can end up working on the same issue

**Comment by ManishBisht777** [comment]
the mentorship button text is being changed in #222 so we don't have to remove the button alltogether

**Comment by ManishBisht777** [comment]
Closing this as not planned
