### ISSUE TITLE
[Feat] To add interview questions inside - Learn Batch > JavaScript > DOM Manipulation

### ISSUE THREAD

**Issue by hemant14050** [FrontendFreaks/Official-Website#233]
### Todo:
- To add Interview Questions Tab
- To add some commonly asked interview question on DOM manipulation
- To add solutions for each question

### Current status (No Interview Questions)
![image](https://github.com/FrontendFreaks/Official-Website/assets/112842857/02c5f554-d9ca-4c3a-b6e0-87bd2ffdbe18)

**Comment by hemant14050** [comment]
I want to work on it!
Please assign it to me.

**Comment by ManishBisht777** [comment]
Sure @hemant14050 Assigned to you
