### ISSUE TITLE
Update Twitter Icon

### ISSUE THREAD

**Issue by Divjot02** [FrontendFreaks/Official-Website#235]
### Issue Description 
Currently, the **old Twitter icon** is used.
We should consider updating this icon to the new Twitter logo to maintain a modern and consistent visual identity.

### Screenshot

Current 
![IMG_20231022_035449](https://github.com/FrontendFreaks/Official-Website/assets/140320635/26e5063c-b5d8-4302-a288-19172e1322dd)

**Comment by Divjot02** [comment]
Hey, if there is a need for this update, I would appreciate  if you could assign it to me. I am open to any suggestions or guidance you may have.

**Comment by ManishBisht777** [comment]
sure @Divjot02 Assigned to you :)
