### ISSUE TITLE
[Bug] : Inconsistent footer between home page and other routes

### ISSUE THREAD

**Issue by AKACHI-4** [FrontendFreaks/Official-Website#236]
## What ?

I would like to fix the inconsistent footer among the pages the social icons are only appearing for home page not other. But the thing is that it should be consistent for all.

## Screenshots

- ### FrontendFreaks Page
![image](https://github.com/FrontendFreaks/Official-Website/assets/99159580/a75031af-9cdd-40c0-a56a-d1c902d8c959)

- ### Learn Page
![image](https://github.com/FrontendFreaks/Official-Website/assets/99159580/919b1405-727b-4c4a-b9eb-0b8b25570058)

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<br>

> **Kindly assign it to me under _HacktoberFest'23_** 
> **I will surely complete it ASAP**

**Comment by ManishBisht777** [comment]
sure @AKACHI-4 Assigned to you :)
