### ISSUE TITLE
[Feat] Turn the light-dark mode button into a toggle switch

### ISSUE THREAD

**Issue by karthiknadar1204** [FrontendFreaks/Official-Website#40]
### Description

Currently the navbar has a button for light and dark mode which on clicking gives option to opt for a mode, I propose to make it more dynamic by adding a toggle switch which would dynamically detect the colour of the page and change the colour accordingly

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under hacktberfest2023

**Comment by ManishBisht777** [comment]
All your's @karthiknadar1204  Assigned to you

**Comment by Amandeep-Chauhan** [comment]
Hi @Vishal-raj-1 and @ManishBisht777, I have resolved the issue please review my PR https://github.com/FrontendFreaks/Official-Website/pull/78
