### ISSUE TITLE
CSS issues on homepage

### ISSUE THREAD

**Issue by saniyasaher20** [FrontendFreaks/Official-Website#41]
### Description

- [ ] In the **"Our Batches**" section of HOME page, the font size of the cards' text is too small. Also, this font size does not match with other areas of the website. I request to change the font size.
- [ ] In the "**Footer**" section of HOME page, while hovering the links, they are not properly visible. The hover colour of the links should be changed in dark mode as well as in light mode.

### Screenshots

1.  OUR BATCHES SECTION
![image](https://github.com/FrontendFreaks/Official-Website/assets/43143907/fb808182-7f2a-4feb-a566-dd897a28847e)

2. FOOTER SECTION 
![image](https://github.com/FrontendFreaks/Official-Website/assets/43143907/58fe58a9-5d1a-4f82-bc54-861a97f731a8)

**Comment by saniyasaher20** [comment]
Please assign this to me.

**Comment by ManishBisht777** [comment]
Thanks for raising  an issue all your's @saniyasaher20 assigned to you

**Comment by Amandeep-Chauhan** [comment]
Hi @Vishal-raj-1 and @ManishBisht777, I have resolved the issue please review my PR https://github.com/FrontendFreaks/Official-Website/pull/68
