### ISSUE TITLE
OnClicking the Title like "HTML" dropdown should open

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#43]
### Description

Right now if you click on "Arrow"  then only content is expanding or collapsing. It would be great to click the title content to expand or collapse.

Refer ScreenShot for more infoto 

### Screenshots

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/be990c2b-973b-42eb-a1f6-5ecfe28c6f4f)

**Comment by ChaudaryHammad** [comment]
Hi Vishal! I want to work on this issue. Kindly assign me.

**Comment by Vishal-raj-1** [comment]
There is no need of assigning issue, just go, solve and raise the PR. The First PR which solve that issue will be merged
