### ISSUE TITLE
[DOCS] Add Source Code of CSS Introduction Video

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#44]
### Description

Currently Source Code of CSS Introduction Video is not there. You can copy the source code from this [repo](https://github.com/FrontendFreaks/Learn-HTML-CSS-JS/blob/main/CheatSheets/CSS.md)

### Screenshots

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/f3d0f7a9-8554-49a2-94cb-585ea29d0814)

**Comment by prashant226** [comment]
please assign sir

**Comment by Rishi2602** [comment]
Hi, I would like to work on this issue and complete it soon.

**Comment by Shyam3050** [comment]
i completed and raised pr
