### ISSUE TITLE
[DOCS] : Add Source Code of JavaScript Intro Video

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#46]
### Description

Currently Source Code of JavaScript Intro Video is not there. You can copy the source code from this [repo](https://github.com/FrontendFreaks/Learn-HTML-CSS-JS/blob/main/CheatSheets/JS.md)

**Comment by abhie16** [comment]
@Vishal-raj-1 hello sir I would like to work on this pls assign to me
