### ISSUE TITLE
[DOCS] : Add Source Code of JavaScript DOM Video

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#47]
### Description

Currently Source Code of JavaScript DOM Video is not there. You can copy the source code from this [repo](https://github.com/FrontendFreaks/Learn-HTML-CSS-JS/blob/main/CheatSheets/JavaScript%20DOM.md)

**Comment by abhie16** [comment]
@Vishal-raj-1 hello sir, I would like to work on this pls assign this to me

**Comment by Shyam3050** [comment]
i am working

**Comment by Shyam3050** [comment]
Please close the issue it was already solved when the CSS was merged
