### ISSUE TITLE
[DOCS] : Add Source Code of CSS Grid Video

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#48]
### Description

Currently Source Code of CSS Grid Video is not there. You can copy the source code from this [repo](https://github.com/FrontendFreaks/Learn-HTML-CSS-JS/blob/main/CheatSheets/CSS%20Grid.md)

**Comment by Huzaifa785** [comment]
Hey! I'll add the source code soon, working on it 👨🏻‍💻
