### ISSUE TITLE
[Bug] Remove Search Documentation Bar

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#50]
### Description

We don't need Search Bar right now.

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/66da41ef-c326-4511-a4f2-99093a45fac0)

**Comment by Huzaifa785** [comment]
Hey! I'll remove the search bar soon 👍🏼

**Comment by Vishal-raj-1** [comment]
All the best @Huzaifa785
