### ISSUE TITLE
[Bug] Update the GitHub link on Raise a Issue

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#51]
### Description

Right Now, Raise a Issue on "@github" points to manish repo. It should point to [FrontendFreaks repo](https://github.com/FrontendFreaks/Official-Website).

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/741e07b6-f04f-4b7e-9b8b-9c6bbc8f2023)

**Comment by Jayakumar03** [comment]
Hi 
I would like to work on this issue.

**Comment by hemant14050** [comment]
Could you please assign this issue to me?

**Comment by charann29** [comment]
Hello  @Vishal-raj-1 I'd like to work on this issue and add the necessary -p flag to bypass the corporate proxy. Could you please assign this issue to me?

Also, it would be great if we could add the "hacktoberfest" label to it.

Thank you!

**Comment by sanjaygupta972004** [comment]
Hello @Vishal-raj-1  Sir I would like to work on your FrontendFreaks Repo, Can you assign me this Issue? I will try to solve it!

**Comment by rahulm-28** [comment]
Could you please assign this issue to me?

**Comment by tech-saurabh382** [comment]
i'm working on these issue these is my first contribution

**Comment by saniyasaher20** [comment]
I think it's already solved. The @github link on the website is pointing to the correct [FrontendFreaks repo](https://github.com/FrontendFreaks/Official-Website).
