### ISSUE TITLE
GitHub icon should link to GitHub repo not live website

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#52]
### Description

Right top corner GitHub Icon should point to Frontend Freaks Repo.

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/2f8f035a-1733-49a3-9b96-8866b5415e20)

**Comment by Jayakumar03** [comment]
Hi 
I would like work on this issue

**Comment by hemant14050** [comment]
Could you please assign this issue to me? 
I'm eager to contribute to the project. Thank you!!

**Comment by ManishBisht777** [comment]
@hemant14050 Sorry but @Jayakumar03 Asked first so assigned to this you, there are some more issues you can try

**Comment by ManishBisht777** [comment]
@hemant14050 you can try #51 if you like

**Comment by hemant14050** [comment]
> @hemant14050 you can try #51 if you like

Thanks for suggesting, Please assign it to me.

**Comment by Sanjeetsahu29** [comment]
I want to work on this issue, and I have solved the issue on my local device after cloning the repo. But while pushing the update on my created branch, it's giving me an error. Please help me where I'm doing it wrong if there is so.

remote: Permission to FrontendFreaks/Official-Website.git denied to Sanjeetsahu29.
fatal: unable to access 'https://github.com/FrontendFreaks/Official-Website.git/': The requested URL returned error: 403

**Comment by letsbecometechie** [comment]
Hi @ManishBisht777 and @Vishal-raj-1,

This issue is fixed as part of PR #66. Please review and let me know if anything further needs to be done.
