### ISSUE TITLE
[Feat] Expand and collapse batches

### ISSUE THREAD

**Issue by Vishal-raj-1** [FrontendFreaks/Official-Website#53]
### Description

By Default, All batches are expanded. It would be great if user can expand and collapse batch (like if you want to learn HTML, CSS, JS, you don't need to see other batches like Hire or Build)

![image](https://github.com/FrontendFreaks/Official-Website/assets/59874304/e9b9dae4-95d7-4f01-bb66-06a177ad1525)

**Comment by ankit1296** [comment]
does it mean that if learn batch expanded then hire/build batch should get collapse. only 1 batch should be expanded at a time or by default all batches collapsed and whichever branch you click will get expanded ?

**Comment by ankit1296** [comment]
I would like to work on this

**Comment by Akash-pugazh** [comment]
Hey @ankit1296 Really sorry I've not noticed that you've liked to work on this, forgive me👍
