### ISSUE TITLE
Little update in readme

### ISSUE THREAD

**Issue by nsundriyal62** [FrontendFreaks/Official-Website#75]
### Description

I am searching for the link of main website but not able to find it. I am new to open source and thinks that main link should be in readme.

Sorry if I am making a  wrong assumption.
If not then you can assign this to me.

Thanks for your time.

**Comment by ManishBisht777** [comment]
hey @nsundriyal62 thanks for easing this issue but this is duplicate to #10 

so to avoid confusion we ar closing this issue. feel free to work on #10  if you like tough
