### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by Tanmay-Joshi73** [FrontendFreaks/Official-Website#80]
- >  #CSS Notes
- > # CSS Backgrounds and Gradients
- > 
![Screenshot (49)](https://github.com/FrontendFreaks/Official-Website/assets/124510117/66a36e66-e6fe-4f46-a185-73205bcbbf5a)

```css
 /* Using a background image */
 .container {
   background-image: url(bg.jpg);
 }
- > For a beginner, it's important to know that you can use different types of image files for background images. such as
- .PNG
- .SVG
- .GIF
but we specify only one there

**Comment by nsundriyal62** [comment]
can you assign this to me sir ?

**Comment by Tanmay-Joshi73** [comment]
Can you assign me to this issue?

**Comment by Vishal-raj-1** [comment]
Hey @Tanmay-Joshi73 go ahead
