### ISSUE TITLE
Documentation Missing

### ISSUE THREAD

**Issue by Tanmay-Joshi73** [FrontendFreaks/Official-Website#82]
![image](https://github.com/FrontendFreaks/Official-Website/assets/124510117/f3acc03d-192c-480a-9709-4243550f5422)

> In the Learn-Javascript-Dom Manipulation
> we specify **🎨 Changing style of HTML element using JavaScript** 
but its not present in that page so we should remove  **🎨 Changing style of HTML element using JavaScript** from the page

**Comment by Tanmay-Joshi73** [comment]
Could you please assign me this issue so that I can start working on it?

**Comment by Abhish7k** [comment]
Hey @Tanmay-Joshi73, I think instead of removing the point "🎨Changing style of HTML element using JavaScript", it would be better to add the code for it in the notes section below.

**Comment by Tanmay-Joshi73** [comment]
Yes, I Can Do That. Can u assigned me ?

**Comment by Abhish7k** [comment]
I am not the maintainer so I cannot assign you but you can start working on it anyways.

**Comment by Tanmay-Joshi73** [comment]
i have corrected the issue. Should I wait for the maintainer to assign it to me

**Comment by Shyam3050** [comment]
raise a pr

**Comment by Tanmay-Joshi73** [comment]
ok
