### ISSUE TITLE
[Feat] Link docs

### ISSUE THREAD

**Issue by ManishBisht777** [FrontendFreaks/Official-Website#88]
### Description

Currently, we have a [docs](https://frontendfreaks.vercel.app/docs) for contributing, getting started and overall folder structure but it is not linked 

Add the Docs section to the navbar itself  with `learn build hire docs`

https://frontendfreaks.vercel.app/docs this is the link for the docs

**Comment by nsundriyal62** [comment]
Can you please assign this to me

**Comment by Vishal-raj-1** [comment]
Hey @nsundriyal62 go ahead

**Comment by AjinkyaD3** [comment]
I would like to work on it . Please Assign it to me

**Comment by nsundriyal62** [comment]
this issue is resolved sir 
you can close this now
@Vishal-raj-1
